'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FacialAnimation.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bmpmaMIC10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMIC9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMICEYECLOSED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMICEYECLOSED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMICEYENARROW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMICEYENARROW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmaMICFULL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMICFULL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMIC9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMICEYECLOSED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMICEYECLOSED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMICEYENARROW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMICEYENARROW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmpmMICFULL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMICFULL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
