'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ProjectResources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FacialAnimation.ProjectResources", GetType(ProjectResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMIC9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMIC9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMICEYECLOSED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMICEYECLOSED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMICEYENARROW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMICEYENARROW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmaMICFULL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmaMICFULL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMIC9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMIC9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMICEYECLOSED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMICEYECLOSED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMICEYENARROW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMICEYENARROW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpMICFULL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpMICFULL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMIC9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMIC9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMICEYECLOSED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMICEYECLOSED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMICEYENARROW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMICEYENARROW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bmpmMICFULL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmpmMICFULL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
